import bge


def get_vehicle_parts():
    items = {1: ["primitive bolted armor", "armor", "CHASSIS", 0, 2, 1, 1, 1, 1, "SOFT", 0, 0,
                 "Early attempts at vehicle armor used ordinary unhardened steel, bolted together. Poor protection but cheap."],
             2: ["riveted plate armor", "armor", "CHASSIS", 1, 1, 1, 0.5, 1, 1, "RIVETED", 0, 0,
                 "Not robust, however very easy to make with simple techniques."],
             3: ["extra top armor", "armor", "CHASSIS", 1, 2, 1, 1, 0, 1, "TOP ARMOR", 0, 0,
                 "Top armor on the vehicle is increased."],
             4: ["extra belly armor", "armor", "CHASSIS", 1, 2, 1, 1, 0, 1, "TOP ARMOR", 0, 0,
                 "Thick armor plates with sandbags better protect the crew and equipment from landmines."],
             5: ["applique patches", "armor", "CHASSIS", 2, 1, 1, 0.5, 0, 1, "CRITICAL PROTECTION", 0, 0,
                 "Applied to critical areas. Reduced chance of critical hit."],
             6: ["cast armor", "armor", "CHASSIS", 2, 2, 2, 2, 4, 3, "CAST", 0, 0,
                 "Easy to make but can have flaws. Can be very thick."],
             7: ["hardened armor", "armor", "CHASSIS", 3, 1, 1, 0.5, 2, 3, "THIN", 0, 0,
                 "Welded, extra hardening gives good protection but limits maximum armor thickness."],
             8: ["rolled plate armor", "armor", "CHASSIS", 3, 3, 1, 1.5, 3, 4, "PLATE", 0, 0,
                 "Welded, rolling increases strength and shock resistance. Minimal spalling."],
             9: ["large rolled plates", "armor", "CHASSIS", 4, 4, 1, 2, 5, 5, "PLATE", 0, 0,
                 "Welded, rolling increases strength and shock resistance. Minimal spalling."],
             10: ["large cast section", "armor", "CHASSIS", 5, 3, 2, 3, 8, 6, "CAST", 0, 0,
                  "Requires special techniques to make large sections. Can be very thick."],
             11: ["spaced armor", "armor", "CHASSIS", 6, 2, 1, 1, 0, 6, "SPACED", 0, 0,
                  "Added space between armor layers, either outside as skirts or inside to protect against shaped charge attacks."],
             12: ["composite armor", "armor", "CHASSIS", 7, 1, 1, 0.5, 2, 6, "COMPOSITE", 0, 0,
                  "Advanced prototype armor made from a sandwich of different materials. Resistant to shaped charges."],
             13: ["gunnery station", "crew", "CREW", 0, 2, 1, 1, 2, 0, "NOTHING", 0, 0,
                  "More crew means faster reloading and more redundancy."],
             14: ["primitive driving station", "crew", "CREW", 0, 3, 1, 1.5, 1, 0, "DRIVER", -1, 0,
                  "Every vehicle needs at least one driver. Additional drivers increase redundancy."],
             15: ["commanders station", "crew", "CREW", 1, 2, 1, 1, 1, 0, "COMMANDER", 0, 0,
                  "Addition of a commander gives improved visual range, accuracy and awareness."],
             16: ["primitive radio operator", "crew", "CREW", 1, 3, 1, 1.5, 0, 0, "RADIO", 0, 0,
                  "Gives more flexibility and awareness in combat."],
             17: ["mechanic station", "crew", "CREW", 1, 3, 1, 1.5, 0, 0, "MECHANIC", 0, 0,
                  "A mechanic is better able to make repairs in the field than normal crew and improves reliability."],
             18: ["expert commanders station", "crew", "CREW", 2, 2, 1, 1, 2, 0, "COMMANDER", 0, 0,
                  "Well trained commanders can greatly improve vehicle performance."],
             19: ["radio operator", "crew", "CREW", 2, 2, 1, 1, 0, 0, "RADIO", 0, 0,
                  "Training in electronics and code breaking make expert radio operators a valuable asset."],
             20: ["driving station", "crew", "CREW", 2, 2, 1, 1, 1, 0, "DRIVER", -1, 0,
                  "Improvements to vehicle controls allow for a drivers controls to take up less room."],
             21: ["expert gunnery station", "crew", "CREW", 2, 2, 1, 1, 3, 0, "NOTHING", 0, 0,
                  "Special training and single stage ammunition helps produce gunners who can load faster."],
             22: ["divisional radio operator", "crew", "CREW", 2, 2, 2, 2, 0, 0, "ANTENNA", 0, 0,
                  "A large high powered antenna and radio allows co-ordination of a whole army division."],
             23: ["commander with cupola", "crew", "CREW", 3, 2, 1, 1, 2, 0, "COMMANDERS CUPOLA", 0, 0,
                  "An armored cupola with binocular periscope and advanced rangefinder for the vehicle commander."],
             24: ["expert mechanic station", "crew", "CREW", 3, 2, 1, 1, 0, 0, "MECHANIC", 0, 0,
                  "Improved training and equipment for mechanics allows them to do twice the work in less space."],
             25: ["part-time radio operator", "crew", "CREW", 4, 2, 1, 1, 2, 0, "RADIO", 0, 0,
                  "An improved radio which requires little attention to operate allowing the crew member to also act as a gunner."],
             26: ["advanced gunnery station", "crew", "CREW", 4, 3, 1, 1.5, 5, 0, "IMPROVED SIGHTS", 0, 0,
                  "Special advanced sights and a semi-automatic ammo loader help increase the effectiveness of the gunner."],
             27: ["advanced commanders station", "crew", "CREW", 5, 3, 1, 1.5, 2, 0, "NIGHT VISION CUPOLA", 0, 0,
                  "Equipped with an armored cupola for protection and experimental infra red scope for finding hidden enemies."],
             28: ["gun carriage", "design", "CHASSIS", 0, 1, 1, 0.5, 0, 2, "GUN CARRIAGE", -2, 0,
                  "DEVELOPMENT: Can't be added in game, turns the vehicle in to a towed gun carriage."],
             29: ["primitive drive parts", "design", "DRIVE", 0, 1, 1, 0.5, 0, 1, "BAD HANDLING", -2, 0,
                  "The transmission, gearbox and controls on this chassis are primitive. This gives poor handling on and off road."],
             30: ["unreliable parts", "design", "CHASSIS", 0, 1, 1, 0.5, 0, 1, "UNRELIABLE", -2, 0,
                  "Some parts on this chassis are very unreliable. It is more likely to break down."],
             31: ["dangerous design", "design", "ENGINE", 0, 1, 1, 0.5, 0, 1, "DANGEROUS", -2, 0,
                  "The fuel line, ammo storage, fuel tank or other system on this vehicle is prone to fire and explosion."],
             32: ["wheeled drive", "design", "DRIVE", 0, 1, 1, 0.5, 0, 1, "WHEELED", -2, 0,
                  "This chassis is wheeled. Faster on roads, slower off road."],
             33: ["open top", "design", "CHASSIS", 0, 1, 1, 0.5, 0, 1, "OPEN TOP", -2, 0,
                  "This vehicle has an open top. No top armor, but overall weight is greatly reduced."],
             34: ["open turret", "design", "CHASSIS", 0, 1, 1, 0.5, 0, 1, "OPEN TURRET", -2, 0,
                  "This turret is open. No top armor but turret weight is reduced."],
             35: ["bulkhead", "design", "CHASSIS", 0, 1, 1, 0.5, 0, 4, "BULKHEAD", -2, 0,
                  "Space taken up by internal bulkheads. Increases durability."],
             36: ["weak spot", "design", "CHASSIS", 0, 1, 1, 0.5, 0, 1, "WEAK SPOT", -2, 0,
                  "A weak spot in the design. Perhaps a oversized vision port or unarmored vent cover."],
             37: ["gun mantlet", "design", "CHASSIS", 1, 1, 1, 0.5, 0, 4, "MANTLET", -2, 0,
                  "Weapons are installed in special armored mounts for better protection from critical hits."],
             38: ["armored sponson", "design", "CHASSIS", 1, 1, 1, 0.5, 0, 4, "SPONSON", -2, 0,
                  "Weapons are installed in special armored mounts for better protection from critical hits."],
             39: ["escape hatch", "design", "CHASSIS", 1, 1, 1, 0.5, 0, 2, "ESCAPE HATCH", -2, 0,
                  "An easy to reach escape hatch gives the crew a good chance of survival."],
             40: ["tracked drive", "design", "DRIVE", 1, 1, 1, 0.5, 3, 3, "TRACKED", -2, 0,
                  "This chassis is fully tracked. Good off road movement."],
             41: ["halftrack drive", "design", "DRIVE", 1, 1, 1, 0.5, 2, 2, "HALFTRACK", -2, 0,
                  "This chassis half caterpillar tracks and road wheels. A good compromise."],
             42: ["super- structure", "design", "CHASSIS", 1, 1, 1, 0.5, 0, 2, "SUPERSTRUCTURE", -2, 0,
                  "This vehicle has a hump which houses the gun crew and gun somewhat like a fixed turret."],
             43: ["anti aircraft mount", "design", "WEAPON", 2, 1, 1, 0.5, 0, 1, "AA MOUNT", -2, 0,
                  "Open turret, no armor. Turret guns can be fired as anti aircraft guns."],
             44: ["wide tracks/ wheels", "design", "DRIVE", 3, 1, 1, 0.5, 0, 2, "WIDE TRACKS", -2, 0,
                  "This vehicle has wider tracks or wheels giving better traction on soft terrain."],
             45: ["amphibious adaptation", "design", "DRIVE", 3, 1, 1, 0.5, 0, 2, "AMPHIBIOUS", -2, 0,
                  "This chassis can travel safely through water or over land."],
             46: ["sloped arrangement", "design", "CHASSIS", 3, 1, 1, 0.5, 0, 2, "SLOPED", -2, 0,
                  "The armor here is sloped, which gives a chance of deflecting shells which don't overmatch it."],
             47: ["rocket mount", "design", "WEAPON", 3, 1, 1, 0.5, 0, 1, "ROCKET MOUNT", -2, 0,
                  "Rockets can be mounted in this section."],
             48: ["primitive engine", "engine", "ENGINE", 0, 2, 1, 1, 1, 3, "UNRELIABLE", -1, 0,
                  "An outdated and underpowered civilian engine. When pushed to the limits reliability suffers."],
             49: ["large primitive engine", "engine", "ENGINE", 0, 2, 2, 2, 3, 6, "UNRELIABLE", -1, 0,
                  "An old fashioned industrial engine, from construction or farming machinery."],
             50: ["car engine", "engine", "ENGINE", 1, 1, 1, 0.5, 1, 2, "CHEAP", -1, 0,
                  "A civilian car engine. Slightly underpowered but very reliable."],
             51: ["truck engine", "engine", "ENGINE", 1, 2, 1, 1, 2, 3, "NOTHING", -1, 0,
                  "A large civilian engine, from a bus or truck, quite reliable but not very powerful."],
             52: ["Industrial engine", "engine", "ENGINE", 1, 4, 2, 4, 8, 12, "RELIABLE", -1, 0,
                  "A modified engine from industrial machinery. Huge and inefficient but powerful and reliable."],
             53: ["boat engine", "engine", "ENGINE", 2, 4, 1, 2, 5, 4, "NOTHING", -1, 0,
                  "A compact civilian engine from a large boat. A lot of power gives good off road performance."],
             54: ["luxury engine", "engine", "ENGINE", 3, 2, 1, 1, 3, 1, "NOTHING", -1, 0,
                  "A special engine from luxury or racing cars. Smooth and powerful, only the best."],
             55: ["radial engine", "engine", "ENGINE", 3, 3, 1, 1.5, 5, 2, "NOTHING", -1, 0,
                  "A radial aircraft engine. Good performance for its size."],
             56: ["performance engine", "engine", "ENGINE", 3, 4, 1, 2, 6, 6, "UNRELIABLE", -1, 0,
                  "A high performance engine designed for an aircraft or speedboat."],
             57: ["heavy duty engine", "engine", "ENGINE", 3, 5, 1, 2.5, 7, 8, "CHEAP", -1, 0,
                  "A powerful marine engine, built for endurance, reliability and ease of manufacture."],
             58: ["synthetic fuel engine", "engine", "ENGINE", 6, 5, 1, 2.5, 7, 8, "SYNTHETIC FUEL", -1, 0,
                  "A modified marine engine set up to use experimental synthetic fuel. Can keep going even during fuel shortages."],
             59: ["marine engine", "engine", "ENGINE", 3, 4, 3, 6, 20, 18, "NOTHING", -1, 0,
                  "A huge, powerful engine from a small ship or boat. For the biggest vehicles."],
             60: ["large radial engine", "engine", "ENGINE", 4, 4, 1, 2, 9, 3, "UNRELIABLE", -1, 0,
                  "A large radial aircraft engine. Excellent power to weight ratio."],
             61: ["aircraft engine", "engine", "ENGINE", 4, 3, 2, 3, 12, 7, "UNRELIABLE", -1, 0,
                  "A big aircraft engine. Fragile and high maintenance."],
             62: ["turbo- charged engine", "engine", "ENGINE", 5, 1, 1, 0.5, 2, 2, "UNRELIABLE", -1, 0,
                  "A specially designed car engine with a turbo charger. Increases power without increasing bulk."],
             63: ["unitized modular engine", "engine", "ENGINE", 5, 5, 1, 2.5, 9, 3, "CHEAP", -1, 0,
                  "A large radial aircraft engine mounted on rails for easy removal and replacement or repair."],
             64: ["super- charged engine", "engine", "ENGINE", 5, 4, 2, 4, 18, 7, "NOTHING", -1, 0,
                  "A big aircraft engine with the addition of a supercharger. Increases power without increasing bulk."],
             65: ["high-octane fuel engine", "engine", "ENGINE", 6, 3, 1, 1.5, 8, 3, "DANGEROUS", -1, 0,
                  "A small radial aircraft engine set up to use experimental volatile high octane fuel. Prone to catching fire."],
             66: ["compact large engine", "engine", "ENGINE", 6, 5, 1, 2.5, 13, 3, "UNRELIABLE", -1, 0,
                  "A powerful design featuring many space saving and weight reduction techniques. Expensive and unreliable."],
             67: ["turboshaft engine", "engine", "ENGINE", 7, 6, 1, 3, 20, 3, "TURBOSHAFT", -1, 0,
                  "An experimental jet turbine engine. Very high power to weight ratio. Very expensive, noisy and unreliable."],
             68: ["primitive leaf-spring", "suspension", "DRIVE", 0, 2, 1, 1, 3, 1, "LEAF SPRING", -1, 0,
                  "Simple leaf spring arrangement. Easy to build but not suitable for heavy vehicles."],
             69: ["coil spring", "suspension", "DRIVE", 1, 1, 1, 0.5, 2, 1, "COIL SPRING", -1, 0,
                  "Compact but weak suspension, easy to repair and good off road handling."],
             70: ["leaf spring", "suspension", "DRIVE", 2, 2, 1, 1, 6, 2, "LEAF SPRING", -1, 0,
                  "Simple leaf spring arrangement. Robust and cheap."],
             71: ["conical spring", "suspension", "DRIVE", 3, 1, 1, 0.5, 4, 1, "CONICAL SPRING", -1, 0,
                  "An improvement over normal coiled spring suspension allows for less bulk."],
             72: ["leaf spring bogie", "suspension", "DRIVE", 3, 2, 1, 1, 7, 3, "LEAF SPRING", -1, 0,
                  "Mounting the suspension on the exterior of the vehicle makes repair easier and saves space."],
             73: ["bell crank", "suspension", "DRIVE", 4, 3, 1, 1.5, 10, 2, "BELL CRANK", -1, 0,
                  "Good all terrain performance, Quite unstable. Bulky mounting restricts it to larger vehicles."],
             74: ["torsion bar suspension", "suspension", "DRIVE", 4, 3, 1, 1.5, 10, 3, "TORSION BAR", -1, 0,
                  "A well balanced, stable and robust system. Needs to be long in order to support much weight though."],
             75: ["bell crank bogie", "suspension", "DRIVE", 5, 2, 1, 1, 10, 3, "BELL CRANK", -1, 0,
                  "Good all terrain performance, Quite unstable. Mounting switched to a compact, easy to maintain bogie."],
             76: ["conical spring bogie", "suspension", "DRIVE", 6, 1, 1, 0.5, 5, 3, "CONICAL SPRING", -1, 0,
                  "Conical coiled springs mounted in a modular bogie. Simple, easy to repair with good handling."],
             77: ["twin torsion suspension", "suspension", "DRIVE", 6, 2, 2, 2, 18, 4, "TORSION BAR", -1, 0,
                  "Uses two torsion bars for double the support in a smaller area."],
             78: ["pneumatic suspension ", "suspension", "DRIVE", 6, 4, 1, 2, 10, 3, "PNEUMATIC", -1, 0,
                  "A very stable system with good handling but takes up a lot of room."],
             79: ["hydraulic suspension", "suspension", "DRIVE", 7, 3, 1, 1.5, 12, 3, "HYDRAULIC", -1, 0,
                  "An improvement on pneumatic suspension. More compact and robust."],
             80: ["storage space", "utility", "CHASSIS", 0, 2, 1, 1, 2, 1, "STORES", -1, 0,
                  "Can carry a ton of supplies or two passengers."],
             81: ["fuel tank", "utility", "ENGINE", 1, 1, 1, 0.5, 2, 1, "FUEL", -1, 0,
                  "Need enough fuel to feed your engine."],
             82: ["extra ammo", "utility", "WEAPON", 1, 1, 1, 0.5, 1, 1, "AMMO", 0, 0,
                  "Extra bullets, shells, bombs, rockets or flame thrower fuel."],
             83: ["spare parts", "utility", "CHASSIS", 1, 1, 1, 0.5, 0, 1, "SPARES", 0, 0,
                  "Improves reliability and range in the field."],
             84: ["electric turret control", "utility", "CHASSIS", 1, 1, 1, 0.5, 1, 1, "TURRET CONTROL", 0, 0,
                  "Turret can turn faster, improved weapon stability."],
             85: ["transport section", "utility", "CHASSIS", 1, 4, 2, 4, 10, 1, "STORES", -1, 0,
                  "Can carry 4 tons of supplies or a squad of infantry men (10)."],
             86: ["improved air filters", "utility", "ENGINE", 2, 1, 1, 0.5, 0, 1, "FILTERS", -1, 0,
                  "Gives greatly improved reliability in desert conditions."],
             87: ["sealed hull", "utility", "CHASSIS", 2, 1, 1, 0.5, 3, 2, "SEALED HULL", -1, 0,
                  "Improved chance to move through water terrain."],
             88: ["engineers", "utility", "CREW", 2, 3, 2, 3, 0, 0, "ENGINEERING", -1, 0,
                  "Allows the unit to carry out engineering tasks such as laying mines."],
             89: ["paramedics", "utility", "CREW", 2, 3, 2, 3, 0, 0, "PARAMEDICS", 0, 0,
                  "Medics trained in first aid can help to treat nearby infantry and vehicle crews."],
             90: ["wet ammo storage", "utility", "WEAPON", 3, 1, 1, 0.5, 1, 1, "WET AMMO", 0, 0,
                  "The ammunition on this vehicle is stored in special bins which are protected against fire, and less likely to explode."],
             91: ["special ammo", "utility", "WEAPON", 3, 1, 1, 0.5, 1, 1, "SPECIAL AMMO", 0, 0,
                  "Special ammo where available, such as smoke shells, or improved anti-tank rounds."],
             92: ["improved engine cooling", "utility", "ENGINE", 3, 2, 1, 1, 0, 2, "COOLING", -1, 0,
                  "Improves reliability and crew performance in tropical or desert conditions. "],
             93: ["improved heating", "utility", "ENGINE", 3, 2, 1, 1, 0, 2, "HEATING", -1, 0,
                  "Improves reliability and crew comfort in very cold conditions."],
             94: ["fire suppression system", "utility", "CHASSIS", 4, 1, 1, 0.5, 0, 1, "FIRE EXTINGUISHER", 0, 0,
                  "Gives an chance to extinguish on-board fires when deployed."],
             95: ["smoke launchers", "utility", "WEAPON", 4, 1, 1, 0.5, 0, 1, "SMOKE LAUNCHER", 0, 0,
                  "Can deploy smoke grenades in emergency situations."],
             96: ["improved trans- mission", "utility", "ENGINE", 4, 2, 1, 1, 0, 2, "TRANSMISSION", -1, 0,
                  "Improves overall reliability and off road handling."],
             97: ["hydraulic turret control", "utility", "CHASSIS", 4, 2, 1, 1, 2, 2, "TURRET CONTROL", 1, 0,
                  "Larger turrets can turn faster, improved weapon stability."],
             98: ["expert paramedics", "utility", "CREW", 4, 3, 1, 1.5, 0, 0, "PARAMEDICS", 0, 0,
                  "Improved training and equipment makes for more efficient first aid treatment for nearby soldiers and crew."],
             99: ["electrical trans- mission", "utility", "DRIVE", 4, 4, 1, 2, 0, 4, "ELECTRO TRANSMISSION", -1, 0,
                  "Gives far better handling and performance to heavy vehicles."],
             100: ["gyroscopic stabilizer", "utility", "WEAPON", 5, 2, 1, 1, 0, 2, "STABILIZER", 1, 0,
                   "Reduces penalties from moving and shooting."],
             101: ["advanced ammo", "utility", "WEAPON", 6, 1, 1, 0.5, 1, 1, "ADVANCED AMMO", 0, 0,
                   "Advanced shaped charge shells which can cut through armor at any range using a channeled explosion."],
             102: ["expert engineers", "utility", "CREW", 6, 3, 1, 1.5, 0, 0, "ENGINEERING", -1, 0,
                   "Equipped with plastic explosives and other advanced engineering tools. Improved speed and effectiveness."],
             103: ["primitive machinegun", "weapon", "WEAPON", 0, 2, 1, 1, 0, 1, "NOTHING", 0, 0,
                   "Old fashioned machine gun with a bulky water cooling system and complex mount."],
             104: ["primitive light gun", "weapon", "WEAPON", 0, 3, 1, 1.5, 3, 2, "LOW VELOCITY", 0, 1,
                   "A prototype tank gun. Low velocity gives poor penetration."],
             105: ["machinegun", "weapon", "WEAPON", 1, 1, 1, 0.5, 0, 1, "NOTHING", 0, 0,
                   "Spits out a lot of bullets, keeps infantry away."],
             106: ["light gun", "weapon", "WEAPON", 1, 2, 1, 1, 3, 1, "NOTHING", 0, 1,
                   "A small cannon. Low penetration, small explosive shells."],
             107: ["breech mortar", "weapon", "WEAPON", 0, 2, 2, 2, 8, 2, "MORTAR", 0, 2,
                   "A simple artillery weapon. Low rate of fire but good damage."],
             108: ["primitive heavy gun", "weapon", "WEAPON", 1, 4, 2, 4, 7, 4, "LOW VELOCITY", 0, 2,
                   "A conversion of an old light field gun, readily available."],
             109: ["anti armor rifle", "weapon", "WEAPON", 2, 1, 1, 0.5, 1, 1, "HIGH VELOCITY", 0, 0,
                   "A light, man portable weapon fitted to a vehicle."],
             110: ["auto cannon", "weapon", "WEAPON", 2, 2, 1, 1, 2, 1, "RAPID", 0, 1,
                   "Spits out a lot of small caliber shells. Good vs. infantry."],
             111: ["support gun", "weapon", "WEAPON", 1, 4, 1, 2, 7, 2, "LOW VELOCITY", 0, 2,
                   "Not accurate, low penetration at range. Good vs. buildings."],
             112: ["medium gun", "weapon", "WEAPON", 1, 2, 2, 2, 5, 2, "NOTHING", 0, 3,
                   "A converted naval gun. A good balance of penetration and damage."],
             113: ["heavy breech mortar", "weapon", "WEAPON", 2, 4, 2, 4, 16, 4, "MORTAR", 0, 4,
                   "A very slow rate of fire, but great damage to weight potential."],
             114: ["improved machinegun", "weapon", "WEAPON", 3, 1, 1, 0.5, 0, 1, "RAPID", 0, 0,
                   "More rapid firing than the regular type."],
             115: ["heavy machinegun", "weapon", "WEAPON", 4, 1, 1, 0.5, 1, 1, "NOTHING", 0, 0,
                   "Excellent vs. infantry and light vehicles."],
             116: ["small rockets", "weapon", "WEAPON", 3, 2, 1, 1, 8, 1, "ROCKETS", 2, 10,
                   "Long range rockets with a small warhead. Can saturate an area with explosions."],
             117: ["improved light gun", "weapon", "WEAPON", 3, 3, 1, 1.5, 3, 2, "HIGH VELOCITY", 0, 2,
                   "Longer barrel improves penetration."],
             118: ["heavy support gun", "weapon", "WEAPON", 3, 6, 1, 3, 15, 3, "LOW VELOCITY", 0, 4,
                   "Not accurate, low penetration at range. Good vs. buildings."],
             119: ["heavy gun", "weapon", "WEAPON", 3, 3, 2, 3, 7, 3, "NOTHING", 0, 3,
                   "A compact gun designed especially for anti-tank warfare."],
             120: ["flame- thrower", "weapon", "WEAPON", 3, 3, 2, 3, 1, 3, "FLAMER", 0, 3,
                   "Very high damage potential but very short range."],
             121: ["large rockets", "weapon", "WEAPON", 4, 2, 1, 1, 15, 1, "ROCKETS", 2, 10,
                   "Short range rockets with a large warhead. Can saturate an area with explosions."],
             122: ["improved medium gun", "weapon", "WEAPON", 4, 3, 2, 3, 5, 3, "HIGH VELOCITY", 0, 3,
                   "Improved penetration at all ranges. "],
             123: ["vehicle mounted howitzer", "weapon", "WEAPON", 4, 6, 2, 6, 10, 6, "NO SIGHTS", 0, 5,
                   "Large, not accurate at short ranges or as a direct fire weapon."],
             124: ["heavy auto cannon", "weapon", "WEAPON", 5, 2, 2, 2, 4, 2, "RAPID", 0, 3,
                   "Fires bursts of shells. Can tear up light vehicles or tanks."],
             125: ["improved heavy gun", "weapon", "WEAPON", 5, 6, 2, 6, 8, 6, "HIGH VELOCITY", 0, 5,
                   "Improved penetration and a flat trajectory make for a great anti armor weapon."],
             126: ["super heavy gun", "weapon", "WEAPON", 6, 5, 3, 7.5, 12, 8, "NOTHING", 0, 6,
                   "Not high velocity but can penetrate armor through sheer power."],
             127: ["heavy howitzer", "weapon", "WEAPON", 6, 6, 3, 9, 15, 9, "NO SIGHTS", 0, 6,
                   "Huge, not accurate at short ranges or as a direct fire weapon but decent artillery."],
             128: ["anti tank rockets", "weapon", "WEAPON", 7, 2, 1, 1, 15, 1, "AT ROCKETS", 2, 10,
                   "Specially designed shaped charge rockets can easily penetrate enemy armor."],
             129: ["advanced heavy gun", "weapon", "WEAPON", 7, 4, 1, 2, 8, 2, "NOTHING", 0, 2,
                   "Special weight savings and redesigned recoil system allow good power with less space taken up."]}

    labels = ["name",
              "part_type",
              "critical",
              "level",
              "y_size",
              "x_size",
              "weight",
              "rating",
              "durability",
              "flags",
              "location",
              "visual",
              "description"]

    new_part_dictionary = {}

    for part_key in items:
        part = items[part_key]

        new_part_dict = {}

        for e in range(len(part)):
            entry = part[e]
            label = labels[e]
            new_part_dict[label] = entry

        new_part_dictionary[part_key] = new_part_dict

    return new_part_dictionary

chassis_dict = {1: {"x": 2, "y": 5, "name": "mini chassis", "front": 1, "armor_scale": 1.0},
                2: {"x": 4, "y": 6, "name": "small chassis", "front": 2, "armor_scale": 1.1},
                3: {"x": 6, "y": 8, "name": "medium chassis", "front": 3, "armor_scale": 1.2},
                4: {"x": 8, "y": 10, "name": "large chassis", "front": 4, "armor_scale": 1.3}}

turret_dict = {0: {"x": 0, "y": 0, "name": "no turret", "block_x": 0, "block_y": 0, "armor_scale": 0},
               1: {"x": 2, "y": 2, "name": "mini turret", "block_x": 2, "block_y": 1, "armor_scale": 1.0},
               2: {"x": 2, "y": 3, "name": "small turret", "block_x": 2, "block_y": 2, "armor_scale": 1.1},
               3: {"x": 4, "y": 3, "name": "medium turret", "block_x": 4, "block_y": 2, "armor_scale": 1.2},
               4: {"x": 5, "y": 4, "name": "large turret", "block_x": 4, "block_y": 3, "armor_scale": 1.3},
               5: {"x": 8, "y": 5, "name": "huge turret", "block_x": 6, "block_y": 4, "armor_scale": 1.4}}

drive_dict = {'WHEELED': {'on road': 1.3, 'off road': 0.5, 'stability': 0, 'handling': [5, 1]},
              'HALFTRACK': {'on road': 1.15, 'off road': 0.8, 'stability': 1, 'handling': [4, 2]},
              'TRACKED': {'on road': 1.0, 'off road': 1.0, 'stability': 1, 'handling': [3, 3]}}

suspension_dict = {'LEAF SPRING': {'on road': 2.8, 'off road': 1.9, 'stability': 2, 'handling': [2, 2]},
                   'COIL SPRING': {'on road': 2.0, 'off road': 2.0, 'stability': 2, 'handling': [1, 4]},
                   'CONICAL SPRING': {'on road': 2.5, 'off road': 2.0, 'stability': 2, 'handling': [3, 5]},
                   'BELL CRANK': {'on road': 2.7, 'off road': 2.0, 'stability': 1, 'handling': [2, 3]},
                   'TORSION BAR': {'on road': 3.0, 'off road': 2.1, 'stability': 3, 'handling': [3, 2]},
                   'HYDRAULIC': {'on road': 3.0, 'off road': 2.2, 'stability': 4, 'handling': [3, 4]},
                   'PNEUMATIC': {'on road': 3.0, 'off road': 2.1, 'stability': 4, 'handling': [4, 3]},
                   'UNSPRUNG': {'on road': 0.8, 'off road': 0.56, 'stability': 0, 'handling': [0, 0]}}

color_dict = {"engine": [0.0, 1.0, 0.2, 1.0],
              "suspension": [0.0, 0.1, 1.0, 1.0],
              "utility": [0.1, 0.8, 0.8, 1.0],
              "armor": [0.9, 1.0, 0.0, 1.0],
              "weapon": [1.0, 0.1, 0.0, 1.0],
              "crew": [0.6, 0.0, 1.0, 1.0],
              "empty": [0.8, 0.8, 0.8, 1.0],
              "design": [0.5, 0.5, 0.5, 1.0]}

cammo_dict = {"0": [0.3921568989753723, 0.8313725590705872, 0.2666667103767395, 1.0],
              "1": [0.6666666865348816, 0.729411780834198, 0.32156866788864136, 1.0],
              "2": [0.47058820724487305, 0.501960813999176, 0.47058820724487305, 1.0],
              "3": [0.5960784554481506, 0.8627452850341797, 0.9098039269447327, 1.0],
              "4": [0.729411780834198, 0.572549045085907, 0.41568630933761597, 1.0],
              "5": [0.5176470875740051, 0.21960783004760742, 0.18823528289794922, 1.0],
              "6": [1.0, 0.8749999403953552, 0.6406248807907104, 1.0],
              "7": [1.0, 0.5857142210006714, 0.5428570508956909, 1.0],
              "8": [1.0, 0.9119496941566467, 0.45911943912506104, 1.0],
              "9": [0.3215685784816742, 0.729411780834198, 0.14901959896087646, 1.0],
              "10": [0.40784314274787903, 0.42352941632270813, 0.3607843220233917, 1.0],
              "11": [0.9631901979446411, 1.0, 0.9386503100395203, 1.0], "12": [0.9890109896659851, 1.0, 1.0, 1.0],
              "13": [0.9589040875434875, 1.0, 0.9452055096626282, 1.0],
              "14": [0.501960813999176, 0.6745098829269409, 0.7058823704719543, 1.0],
              "15": [0.10196077823638916, 0.11764708161354065, 0.13333334028720856, 1.0]}

tech_levels = {1: {"aircraft": [0, 0.088],
                   "artillery": [0, 0.144],
                   "design": [2, 0.04],
                   "infantry": [2, 0.04],
                   "espionage": [1, 0.08],
                   "engine": [0, 0.144],
                   "suspension": [0, 0.12],
                   "crew": [1, 0.088],
                   "utility": [0, 0.152],
                   "weapon": [0, 0.104],
                   "armor": [1, 0.12]},
               2: {"aircraft": [0, 0.144],
                   "artillery": [1, 0.112],
                   "design": [2, 0.06],
                   "infantry": [1, 0.08],
                   "espionage": [1, 0.08],
                   "engine": [0, 0.104],
                   "suspension": [0, 0.144],
                   "crew": [1, 0.104],
                   "utility": [0, 0.12],
                   "weapon": [0, 0.104],
                   "armor": [0, 0.088]},
               3: {"aircraft": [1, 0.12],
                   "artillery": [2, 0.0448],
                   "design": [3, 0.02],
                   "infantry": [2, 0.08],
                   "espionage": [1, 0.08],
                   "engine": [2, 0.04],
                   "suspension": [2, 0.04],
                   "crew": [2, 0.04],
                   "utility": [2, 0.064],
                   "weapon": [1, 0.12],
                   "armor": [1, 0.088]},
               4: {"aircraft": [2, 0.064],
                   "artillery": [1, 0.096],
                   "design": [2, 0.064],
                   "infantry": [2, 0.096],
                   "espionage": [2, 0.064],
                   "engine": [1, 0.088],
                   "suspension": [0, 0.12],
                   "crew": [0, 0.152],
                   "utility": [0, 0.12],
                   "weapon": [1, 0.088],
                   "armor": [1, 0.096]},
               5: {"aircraft": [1, 0.12],
                   "artillery": [1, 0.08],
                   "design": [3, 0.024],
                   "infantry": [1, 0.12],
                   "espionage": [2, 0.04],
                   "engine": [1, 0.08],
                   "suspension": [1, 0.08],
                   "crew": [3, 0.068],
                   "utility": [3, 0.016],
                   "weapon": [2, 0.0464],
                   "armor": [1, 0.12]},
               6: {"aircraft": [0, 0.096],
                   "artillery": [0, 0.08],
                   "design": [0, 0.096],
                   "infantry": [0, 0.104],
                   "espionage": [0, 0.072],
                   "engine": [0, 0.064],
                   "suspension": [0, 0.08],
                   "crew": [0, 0.08],
                   "utility": [0, 0.112],
                   "weapon": [0, 0.108],
                   "armor": [0, 0.096]}}

faction_dict = {1: "VINLAND",
                2: "AMORICA",
                3: "HRE",
                4: "JAPAN",
                5: "TURKS",
                6: "MINOR"}
